# Generated by Django 4.2.10 on 2024-05-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcatalog',
            old_name='subcatalog',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='subcatalog',
            old_name='subcategory_name',
            new_name='subcatalog_name',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='category_id',
        ),
    ]
